### ISSUE TITLE
Slowdown of JS Intellisense with the extension enabled

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [master-co/css-language-service#9]
### Description

Hi!

I'm seeing a pretty big slowdown of JS Intellisense with this extension enabled.

With the extension enabled:
![intellislow](https://user-images.githubusercontent.com/110549389/197795777-a2b5d3ad-2404-46a6-bd80-0c4f7933a0f4.gif)

With the extension disabled:
![intellifast](https://user-images.githubusercontent.com/110549389/197795840-c76bd88b-a210-4b4d-82eb-43eeccf54afc.gif)

### Reproduction

1. Enable the extension.
2. Type fun.
Result: Intellisense is slow.

1. Disable the extension and reload the window.
2. Type fun.
Result: Intellisense is fast.

Expected result: Intellisense should be as fast with the extention enabled as it is disabled.

### System Informations

Win10 64
VSCode 1.72.2

**Comment by 1Aron** [comment]
@henrikvilhelmberglund Can you provide hardware specs? We cannot reproduce the problem.

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund Can you provide hardware specs? We cannot reproduce the problem.

To be fair it's an old PC (i7 3.4GHz, 16GB RAM, 1070).

However I think it's related to length of the .js file. In a 7k row file (I just copy pasted lines with comments) it takes several seconds for me for auto completion to kick in with the extension enabled while it's still 10ms with it disabled.

**Comment by 0Miles** [comment]
Intellisense has been optimized in v2.1.4
Try it out after you update👍

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund Intellisense has been optimized in v2.1.4 Try it out after you update👍

Confirmed fixed. Thanks for the fast update!
